import { DAppType } from "./type";

export const ethereumDapps: DAppType[] = [
  {
    dappId: 3,
    name: 'CryptoKitties',
    description: 'In CryptoKitties, users collect and breed adorable creatures.',
    fullDescription: 'In CryptoKitties, users collect and breed oh-so-adorable creatures that we call CryptoKitties! Each kitty has a unique genome that defines its appearance and traits. Players can breed their kitties to create new furry friends and unlock rare cattributes.',
    logo: 'https://dashboard-assets.dappradar.com/geRRcWz9IdTwSrm1/document/3/cryptokitties-dapp-games-eth-logo_43af8137d6219e1fd08b52d9cdfc9447.png',
    website: 'https://www.cryptokitties.co',
    chains: ['eip155:1'],
    categories: ['games'],
    socialLinks: [
      {
        title: 'discord',
        url: 'https://discord.gg/3GvT66U',
        type: 'discord',
      },
      {
        title: 'facebook',
        url: 'https://www.facebook.com/CryptoKitties/',
        type: 'facebook',
      },
      {
        title: 'instagram',
        url: 'https://www.instagram.com/cryptokitties/',
        type: 'instagram',
      },
      {
        title: 'medium',
        url: 'https://medium.com/cryptokitties',
        type: 'medium',
      },
      {
        title: 'other',
        url: 'https://www.cryptokitties.co/blog/',
        type: 'other',
      },
      {
        title: 'reddit',
        url: 'https://www.reddit.com/r/CryptoKitties/',
        type: 'reddit',
      },
      {
        title: 'twitter',
        url: 'https://twitter.com/cryptokitties',
        type: 'twitter',
      },
      {
        title: 'youtube',
        url: 'https://www.youtube.com/channel/UClUgQBJcxAmHjOQgV4QgVXg',
        type: 'youtube',
      },
    ],
  },
  {
    dappId: 4,
    name: 'CryptoFighters',
    description: 'Battle on the blockchain!',
    fullDescription: 'Battle on the blockchain!',
    logo: 'https://dashboard-assets.dappradar.com/geRRcWz9IdTwSrm1/document/4/cryptofighters-dapp-games-ethereum-logo_95f24cd5a0610de0c14eb8d2b6069611.png',
    website: 'https://cryptofighters.io',
    chains: ['eip155:1'],
    categories: ['games'],
    socialLinks: [
      {
        title: 'reddit',
        url: 'https://www.reddit.com/r/CryptoFighters/',
        type: 'reddit',
      },
      {
        title: 'telegram',
        url: 'https://t.me/CryptoFighters',
        type: 'telegram',
      },
      {
        title: 'twitter',
        url: 'https://twitter.com/CryptoFighters',
        type: 'twitter',
      },
    ],
  },
  {
    dappId: 12,
    name: 'CryptoPunks',
    description: 'The first Non-Fungible Token.',
    fullDescription: '10,000 unique collectible characters with proof of ownership stored on the Ethereum blockchain. The project that inspired the modern CryptoArt movement. The first Non-Fungible Token and inspiration for the Ethereum ERC-721 standard that powers most digital art and collectibles.',
    logo: 'https://dashboard-assets.dappradar.com/geRRcWz9IdTwSrm1/document/12/cryptopunks-dapp-collectibles-eth-logo_51a1d3949f57d12b1e9dd04bf3ea4eb3.png',
    website: 'https://www.larvalabs.com/cryptopunks',
    chains: ['eip155:1'],
    categories: ['collectibles'],
    socialLinks: [],
  },
  {
    dappId: 13,
    name: 'OpenSea',
    description: 'OpenSea is the first and largest peer-to-peer marketplace.',
    fullDescription: 'OpenSea is the first and largest peer-to-peer marketplace for crypto collectibles, which include gaming items, digital art, and other virtual goods backed by a blockchain.',
    logo: 'https://dashboard-assets.dappradar.com/geRRcWz9IdTwSrm1/document/13/opensea-dapp-marketplaces-ethereum-logo_a3421ac6e32d529db3c8293f4cfa9bcd.png',
    website: 'https://opensea.io',
    chains: [
      'eip155:421611',
      'eip155:43114',
      'eip155:10',
      'eip155:42161',
      'eip155:1',
      'eip155:8217',
      'eip155:43114',
      'eip155:137',
      'eip155:250',
    ],
    categories: ['marketplaces'],
    socialLinks: [
      {
        title: 'discord',
        url: 'https://discord.gg/zAHt7Tb',
        type: 'discord',
      },
      {
        title: 'facebook',
        url: 'https://facebook.com/projectopensea',
        type: 'facebook',
      },
      {
        title: 'medium',
        url: 'https://medium.com/@opensea',
        type: 'medium',
      },
      {
        title: 'reddit',
        url: 'https://reddit.com/r/opensea',
        type: 'reddit',
      },
      {
        title: 'twitter',
        url: 'https://twitter.com/projectopensea',
        type: 'twitter',
      },
    ],
  },
  {
    dappId: 17,
    name: 'Ethermon',
    description: 'Re-launched in 2019, Ethermon.io is the community-driven version of the popular Etheremon.com.',
    fullDescription: 'Re-launched in 2019, Ethermon.io is the community-driven version of the popular Etheremon.com under an entirely new team. Players can continue to use their old and new Ether Monsters (EtherMon) to join forces and continue their journey in this crypto-based battle game where they capture, train, and transform their collectibles to make their permanent mark on the blockchain.',
    logo: 'https://dashboard-assets.dappradar.com/geRRcWz9IdTwSrm1/document/17/ethermon-dapp-games-eth-logo_9e9239828819afeeccc308f64435fff6.png',
    website: 'https://www.ethermon.io',
    chains: ['eip155:1'],
    categories: ['games'],
    socialLinks: [
      {
        title: 'Official Discord',
        url: 'https://discordapp.com/invite/p7wBXc9',
        type: 'discord',
      },
      {
        title: 'Official Discord',
        url: 'https://discord.gg/xgJpuzc',
        type: 'discord',
      },
      {
        title: 'Official Facebook',
        url: 'https://www.facebook.com/etheremon',
        type: 'facebook',
      },
      {
        title: 'Official Reddit',
        url: 'https://www.reddit.com/r/etheremon/',
        type: 'reddit',
      },
      {
        title: 'Official Telegram',
        url: 'https://t.me/ethermon',
        type: 'telegram',
      },
      {
        title: 'Official Telegram',
        url: 'https://t.me/myetheremon',
        type: 'telegram',
      },
      {
        title: 'Official Twitter',
        url: 'https://twitter.com/Ethermon_io',
        type: 'twitter',
      },
      {
        title: 'Official Twitter',
        url: 'https://twitter.com/myetheremon',
        type: 'twitter',
      },
    ],
  },
  {
    dappId: 18,
    name: 'Edgeless',
    description: 'The Ethereum smart contract powered Casino.',
    fullDescription: 'The Ethereum smart contract powered Casino that offers 0% house edge games and solves the casino transparency question once and for all.',
    logo: 'https://dashboard-assets.dappradar.com/geRRcWz9IdTwSrm1/document/18/edgeless-dapp-gambling-eth-logo_dd6d3dee2958799c7bca33b8a55ecaad.png',
    website: 'https://edgeless.io/',
    chains: ['eip155:1'],
    categories: ['gambling'],
    socialLinks: [
      {
        title: 'BitcoinTalk',
        url: 'https://bitcointalk.org/index.php?topic=1718384.0',
        type: 'other',
      },
      {
        title: 'CoinMarketCap',
        url: 'https://coinmarketcap.com/currencies/edgeless/',
        type: 'other',
      },
      {
        title: 'GitHub',
        url: 'https://github.com/edgeless-casino',
        type: 'github',
      },
      {
        title: 'Official Discord',
        url: 'https://discordapp.com/invite/h8a8Zs3',
        type: 'discord',
      },
      {
        title: 'Official Facebook',
        url: 'https://www.facebook.com/EdgelessCasino',
        type: 'facebook',
      },
      {
        title: 'Official Medium',
        url: 'https://medium.com/Edgeless',
        type: 'medium',
      },
      {
        title: 'Official Reddit',
        url: 'https://www.reddit.com/r/Edgeless/',
        type: 'reddit',
      },
      {
        title: 'Official Telegram',
        url: 'https://t.me/joinchat/FXRVHBFKg-YU0KqZXTCGbQ',
        type: 'telegram',
      },
      {
        title: 'Official Twitter',
        url: 'https://twitter.com/edgelessproject',
        type: 'twitter',
      },
      {
        title: 'Official YouTube',
        url: 'https://www.youtube.com/channel/UC_7GBNR9N2UATqmdEeGjBvA',
        type: 'youtube',
      },
    ],
  },
  {
    dappId: 764,
    name: 'Summer.fi',
    description: 'DeFi made simple and secure: take advantage of powerful automation strategies and user-friendly UX across multiple protocols and layers.',
    fullDescription: 'Summer.fi is a platform for decentralized finance. It can be used to borrow stablecoins against users’ favorite cryptocurrencies, increase exposure against them using Multiply, or Earn a competitive yield. This can be done across multiple protocols and Layers — all in one place. Summer.fi’s mission is to provide the most trusted entry point to deploy capital into DeFi. The team is made of passionate thinkers and builders driven to create a better user experience for all while being able to maximize returns.',
    logo: 'https://dashboard-assets.dappradar.com/geRRcWz9IdTwSrm1/document/764/oasisapp-dapp-defi-764-logo_1e5311680e6fdd95205b13c77d6e2ff0.png',
    website: 'https://summer.fi/',
    chains: ['eip155:43114', 'eip155:42161', 'eip155:1', 'eip155:250', 'eip155:43114'],
    categories: ['defi'],
    socialLinks: [
      {
        title: 'blog',
        url: 'https://blog.summer.fi/',
        type: 'blog',
      },
      {
        title: 'discord',
        url: 'https://discord.gg/summerfi',
        type: 'discord',
      },
      {
        title: 'twitter',
        url: 'https://twitter.com/summerfinance_',
        type: 'twitter',
      },
    ],
  },
  {
    dappId: 598,
    name: 'ETHLend',
    description: 'Decentralized peer-to-peer lending platform based on blockchain.',
    fullDescription: 'Decentralized peer-to-peer lending platform based on blockchain allowing users to use their Bitcoin, Ethereum, and other ERC20 tokens as collateral.',
    logo: 'https://dashboard-assets.dappradar.com/geRRcWz9IdTwSrm1/document/598/ethlend-dapp-other-eth-logo_5d72fa8088b1980b430a40b24a47f4bc.png',
    website: 'https://ethlend.io',
    chains: ['eip155:1'],
    categories: ['other'],
    socialLinks: [
      {
        title: 'Blog',
        url: 'https://blog.ethlend.io/',
        type: 'other',
      },
      {
        title: 'Official Medium',
        url: 'https://medium.com/aave',
        type: 'medium',
      },
      {
        title: 'Official Twitter',
        url: 'https://twitter.com/AaveAave',
        type: 'twitter',
      },
      {
        title: 'Official Twitter',
        url: 'https://twitter.com/ethlend1',
        type: 'twitter',
      },
    ],
  },
]
